# Generated by Django 4.0.2 on 2022-02-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myboard',
            name='mydate',
            field=models.DateTimeField(),
        ),
    ]
